"""Pipeline for assembling spread model input features."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Sequence

import numpy as np
import sqlalchemy as sa
import xarray as xr

from api.core.grid import DEFAULT_CELL_SIZE_DEG, DEFAULT_CRS, GridSpec, GridWindow, get_grid_window_for_bbox
from api.db import get_engine
from api.fires.service import FireHeatmapWindow, get_fire_cells_heatmap, get_region_grid_spec
from api.terrain.window import TerrainWindow, load_terrain_window
from ml.spread.contract import DEFAULT_HORIZONS_HOURS, SpreadModelInput
from ml.weather_bias_correction import (
    WEATHER_BIAS_CORRECTOR_ENV,
    resolve_weather_bias_corrector_path,
    WeatherBiasCorrector,
 )

LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class SpreadInputs:
    """Orchestrated input package for spread models."""

    grid: GridSpec
    window: GridWindow
    active_fires: FireHeatmapWindow
    weather_cube: xr.Dataset
    terrain: TerrainWindow
    forecast_reference_time: datetime
    horizons_hours: Sequence[int] = DEFAULT_HORIZONS_HOURS
    # Metadata flags for error handling and observability
    weather_fallback_used: bool = False
    terrain_fallback_used: bool = False
    # Fire state snapshots at prior time windows.
    # fire_history_t6h: detections from [ref_time - 12h, ref_time - 6h]
    # fire_history_t12h: detections from [ref_time - 18h, ref_time - 12h]
    fire_history_t6h: FireHeatmapWindow | None = None
    fire_history_t12h: FireHeatmapWindow | None = None

    def to_model_input(self) -> SpreadModelInput:
        """Convert to the canonical SpreadModelInput expected by models."""
        return SpreadModelInput(
            grid=self.grid,
            window=self.window,
            active_fires=self.active_fires,
            weather_cube=self.weather_cube,
            terrain=self.terrain,
            forecast_reference_time=self.forecast_reference_time,
            horizons_hours=self.horizons_hours,
            fire_history_t6h=self.fire_history_t6h,
            fire_history_t12h=self.fire_history_t12h,
        )


def _require_tz_aware_utc(dt: datetime, *, field_name: str) -> datetime:
    """Require tz-aware datetime and normalize it to UTC.

    Weather ingest + spread heuristics expect times aligned to UTC and commonly use
    tz-naive UTC `datetime64[ns]` in xarray for selection.
    """
    if dt.tzinfo is None:
        raise ValueError(f"{field_name} must be timezone-aware (UTC recommended). Got tzinfo=None.")
    return dt.astimezone(timezone.utc)


def _as_datetime64_utc_naive(dt: datetime) -> np.datetime64:
    """Convert datetime to tz-naive UTC datetime64[ns] (ingest convention)."""
    if dt.tzinfo is not None:
        dt = dt.astimezone(timezone.utc).replace(tzinfo=None)
    return np.datetime64(dt, "ns")


def _same_window(a: GridWindow, b: GridWindow) -> bool:
    if (a.i0, a.i1, a.j0, a.j1) != (b.i0, b.i1, b.j0, b.j1):
        return False
    # Use strict equality when possible (they should be generated by the same grid math),
    # but allow tiny floating differences in tests/mocks.
    return bool(
        np.allclose(np.asarray(a.lat), np.asarray(b.lat), rtol=0.0, atol=1e-12)
        and np.allclose(np.asarray(a.lon), np.asarray(b.lon), rtol=0.0, atol=1e-12)
    )


def _assert_same_window(*, expected: GridWindow, actual: GridWindow, label: str) -> None:
    if not _same_window(expected, actual):
        raise ValueError(
            f"{label} window does not match requested AOI window. "
            f"expected={(expected.i0, expected.i1, expected.j0, expected.j1)} "
            f"actual={(actual.i0, actual.i1, actual.j0, actual.j1)}"
        )


def assert_grid_alignment(grid: GridSpec) -> None:
    """Hard stop if the grid CRS or cell size diverges from the analysis-grid contract.

    STOP-GEO-CRS: CRS must be EPSG:4326.  Any other projection breaks pixel-level
    lat/lon alignment between fire, weather, and terrain layers.

    STOP-GEO-RES: Cell size must match DEFAULT_CELL_SIZE_DEG (0.01°).  A mismatched
    resolution means train-time features are computed at a different spatial scale than
    inference, invalidating learned spatial relationships.
    """
    if grid.crs != DEFAULT_CRS:
        raise ValueError(
            f"STOP-GEO-CRS: analysis grid CRS={grid.crs!r} does not match the required "
            f"CRS {DEFAULT_CRS!r}. Re-project the grid to EPSG:4326 before assembling "
            f"spread inputs."
        )
    if abs(grid.cell_size_deg - DEFAULT_CELL_SIZE_DEG) > 1e-9:
        raise ValueError(
            f"STOP-GEO-RES: analysis grid cell_size_deg={grid.cell_size_deg!r} does not "
            f"match the training grid cell size {DEFAULT_CELL_SIZE_DEG!r}. Regridding to "
            f"a different resolution is not supported — use the canonical 0.01° grid."
        )


def _resolve_storage_path(path_value: str | Path) -> Path:
    """Resolve artifact storage paths across host/container mount differences.

    In local development we may write absolute host paths (e.g. `/Users/.../data/...`)
    while runtime services execute in containers mounted at `/app/data` and `/app/models`.
    This resolver preserves existing valid paths and remaps common roots when needed.
    """
    original = Path(path_value)
    candidates: list[Path] = []

    def _add_candidate(candidate: Path) -> None:
        if candidate not in candidates:
            candidates.append(candidate)

    _add_candidate(original)

    if not original.is_absolute():
        _add_candidate(Path.cwd() / original)
    else:
        parts = list(original.parts)
        for anchor in ("data", "models"):
            if anchor in parts:
                idx = parts.index(anchor)
                suffix = Path(*parts[idx + 1 :]) if idx + 1 < len(parts) else Path()
                _add_candidate(Path.cwd() / anchor / suffix)

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[-1]


def _is_conus_bbox(bbox: tuple[float, float, float, float]) -> bool:
    """Return True if the bbox is fully within approximate CONUS bounds."""
    min_lon, min_lat, max_lon, max_lat = bbox
    return min_lon >= -125.0 and max_lon <= -66.0 and min_lat >= 22.0 and max_lat <= 50.0


def _get_latest_weather_run(
    ref_time: datetime,
    bbox: tuple[float, float, float, float],
) -> dict | None:
    """Find the latest completed weather run covering the AOI before or at ref_time.

    For CONUS bboxes, HRRR (model_name LIKE 'hrrr%') is preferred over GFS because
    it has 3km resolution and hourly cycles.  Outside CONUS only GFS runs exist so
    the preference has no effect.
    """
    min_lon, min_lat, max_lon, max_lat = bbox
    stmt = sa.text(
        """
        SELECT id, storage_path, run_time, model
        FROM weather_runs
        WHERE status = 'completed'
          AND run_time <= :ref_time
          AND COALESCE(bbox_min_lon, -180.0) <= :min_lon AND COALESCE(bbox_max_lon, 180.0) >= :max_lon
          AND COALESCE(bbox_min_lat, -90.0) <= :min_lat AND COALESCE(bbox_max_lat, 90.0) >= :max_lat
        ORDER BY
          CASE WHEN model LIKE 'hrrr%' THEN 0 ELSE 1 END,
          run_time DESC,
          created_at DESC
        LIMIT 1
        """
    )
    with get_engine().connect() as conn:
        row = conn.execute(
            stmt,
            {
                "ref_time": ref_time,
                "min_lon": min_lon,
                "max_lon": max_lon,
                "min_lat": min_lat,
                "max_lat": max_lat,
            },
        ).mappings().first()
    return dict(row) if row else None


def _load_weather_cube(
    ref_time: datetime,
    window: GridWindow,
    horizons_hours: Sequence[int],
    bbox: tuple[float, float, float, float],
    *,
    weather_bias_corrector_path: Path | None = None,
) -> xr.Dataset:
    """Load and align weather data for the requested window and horizons."""
    run = _get_latest_weather_run(ref_time, bbox)

    if not run:
        LOGGER.warning(
            "No completed weather run found for ref_time=%s and bbox=%s; using calm fallback.",
            ref_time, bbox
        )
        ds = _create_fallback_weather(window, ref_time, horizons_hours)
        ds.attrs["weather_fallback_used"] = True
        ds.attrs["weather_fallback_reason"] = "no_weather_run_found"
        return ds

    raw_path = str(run["storage_path"])
    path = _resolve_storage_path(raw_path)

    if not path.exists():
        LOGGER.warning(
            "Weather run %s file missing at %s (raw=%s); using calm fallback.",
            run["id"],
            path,
            raw_path,
        )
        ds = _create_fallback_weather(window, ref_time, horizons_hours)
        ds.attrs["weather_fallback_used"] = True
        ds.attrs["weather_fallback_reason"] = f"weather_file_missing:{run['id']}"
        return ds

    ds = None
    try:
        # Use chunked/lazy loading to avoid loading entire dataset into memory
        # Chunk along time dimension for efficient slicing of forecast windows
        # This prevents memory issues with large weather files
        chunks = {"time": "auto", "lat": -1, "lon": -1}
        try:
            ds = xr.open_dataset(path, chunks=chunks)
        except ValueError as exc:
            msg = str(exc).lower()
            if "chunk manager dask" in msg or "unrecognized chunk manager" in msg:
                LOGGER.info(
                    "xarray chunk manager unavailable; reopening weather dataset without chunks: %s",
                    path,
                )
                ds = xr.open_dataset(path)
            else:
                raise

        missing_coords = [c for c in ("lat", "lon", "time") if c not in ds.coords]
        if missing_coords:
            LOGGER.warning(
                "Weather dataset at %s missing required coord(s) %s; using fallback.",
                path,
                missing_coords,
            )
            ds_fallback = _create_fallback_weather(window, ref_time, horizons_hours)
            ds_fallback.attrs["weather_fallback_used"] = True
            ds_fallback.attrs["weather_fallback_reason"] = f"missing_coords:{','.join(missing_coords)}"
            return ds_fallback

        missing_vars = [v for v in ("u10", "v10") if v not in ds.data_vars]
        if missing_vars:
            LOGGER.warning(
                "Weather dataset at %s missing required var(s) %s; using fallback.",
                path,
                missing_vars,
            )
            ds_fallback = _create_fallback_weather(window, ref_time, horizons_hours)
            ds_fallback.attrs["weather_fallback_used"] = True
            ds_fallback.attrs["weather_fallback_reason"] = f"missing_vars:{','.join(missing_vars)}"
            return ds_fallback

        # 1) Align to AOI window coords.
        #
        # Weather ingest writes NetCDFs already interpolated onto the shared analysis grid.
        # Prefer exact label-based selection; fall back to nearest for robustness.
        try:
            ds_aligned = ds.sel(lat=window.lat, lon=window.lon)
        except Exception:
            LOGGER.info("Exact lat/lon selection failed for %s; falling back to nearest.", path)
            ds_aligned = ds.sel(lat=window.lat, lon=window.lon, method="nearest")

        # 2) Select requested time horizons (absolute times).
        target_times = [ref_time + timedelta(hours=int(h)) for h in horizons_hours]
        target_times_64 = [_as_datetime64_utc_naive(t) for t in target_times]

        ds_times = ds.coords["time"].values
        if len(ds_times) > 0:
            if target_times_64[0] < ds_times[0] or target_times_64[-1] > ds_times[-1]:
                LOGGER.warning(
                    "Requested horizons %s for ref_time %s are partially outside weather run %s range [%s, %s]",
                    list(horizons_hours),
                    ref_time,
                    run["id"],
                    ds_times[0],
                    ds_times[-1],
                )

        ds_final = ds_aligned.sel(time=target_times_64, method="nearest")
        ds_final = ds_final.assign_coords(
            time=target_times_64,
            lead_time_hours=("time", list(horizons_hours)),
        )

        # Rename ingest-native 'tp' → contract-expected 'precip_24h'.
        if "tp" in ds_final.data_vars and "precip_24h" not in ds_final.data_vars:
            ds_final = ds_final.rename({"tp": "precip_24h"})

        # Ensure the caller doesn't hold an open file handle.
        ds_final = ds_final.load()

        # Optional: apply global bias correction (if configured).
        ds_final = _maybe_apply_weather_bias_correction(
            ds_final, weather_bias_corrector_path=weather_bias_corrector_path
        )
        # Attach equilibrium DFMC derived from T/RH.
        ds_final = _add_dfmc_to_weather(ds_final)
        # Mark as not using fallback when successfully loaded
        ds_final.attrs["weather_fallback_used"] = False
        ds_final.attrs["weather_run_id"] = run.get("id")
        run_time = run.get("run_time")
        if run_time is not None:
            try:
                ds_final.attrs["weather_run_time"] = run_time.isoformat()
            except Exception:
                ds_final.attrs["weather_run_time"] = str(run_time)
        return ds_final
    except Exception:
        LOGGER.exception("Failed to load/align weather dataset from %s; using fallback.", path)
        ds_fallback = _create_fallback_weather(window, ref_time, horizons_hours)
        ds_fallback.attrs["weather_fallback_used"] = True
        ds_fallback.attrs["weather_fallback_reason"] = f"load_exception:{path.name}"
        return ds_fallback
    finally:
        if ds is not None:
            try:
                ds.close()
            except Exception:  # pragma: no cover
                pass


def _compute_dfmc(t2m_k: np.ndarray, rh2m_pct: np.ndarray) -> np.ndarray:
    """Nelson (1984) / NFDRS equilibrium dead fuel moisture content (10-hr).

    Uses the NFDRS piecewise EMC formula.  Returns DFMC as a fraction in [0, 0.40].

    Parameters
    ----------
    t2m_k : np.ndarray
        Air temperature in Kelvin (GFS/HRRR native units).
    rh2m_pct : np.ndarray
        Relative humidity in percent [0, 100].
    """
    t_f = (t2m_k - 273.15) * 9.0 / 5.0 + 32.0  # Kelvin → Fahrenheit
    h = np.clip(rh2m_pct, 0.0, 100.0)

    # NFDRS piecewise EMC (percent)
    low  = 0.03229 + 0.281073 * h - 0.000578 * h * t_f   # h < 10 %
    mid  = 2.22749 + 0.160107 * h - 0.014784 * t_f        # 10 ≤ h < 50 %
    high = 21.0606 + 0.005565 * h**2 - 0.00035 * h * t_f - 0.483199 * h  # h ≥ 50 %

    emc_pct = np.where(h < 10.0, low, np.where(h < 50.0, mid, high))
    emc_pct = np.clip(emc_pct, 0.0, 40.0)
    return (emc_pct / 100.0).astype(np.float32)


def _add_dfmc_to_weather(ds: xr.Dataset) -> xr.Dataset:
    """Compute and attach equilibrium DFMC to a weather cube.

    Requires ``t2m`` (K) and ``rh2m`` (%) variables.  When either is missing or
    all-NaN (e.g. zero-wind fallback cube), a NaN field is attached so downstream
    consumers can detect the gap rather than silently using stale values.
    """
    if "t2m" not in ds.data_vars or "rh2m" not in ds.data_vars:
        LOGGER.warning("Cannot compute DFMC: t2m or rh2m missing from weather cube.")
        shape = tuple(ds.sizes[d] for d in ds.dims if d in ("time", "lat", "lon"))
        if shape:
            ds = ds.assign(dfmc=(list(ds.dims), np.full(shape, np.nan, dtype=np.float32)))
        return ds

    t2m  = np.asarray(ds["t2m"].values,  dtype=np.float32)
    rh2m = np.asarray(ds["rh2m"].values, dtype=np.float32)

    if np.all(np.isnan(t2m)) or np.all(np.isnan(rh2m)):
        LOGGER.debug("t2m/rh2m all-NaN (fallback cube); attaching NaN DFMC.")
        dfmc = np.full_like(t2m, np.nan, dtype=np.float32)
    else:
        dfmc = _compute_dfmc(t2m, rh2m)

    ds = ds.assign(dfmc=(ds["t2m"].dims, dfmc))
    return ds


def _create_fallback_weather(
    window: GridWindow,
    ref_time: datetime,
    horizons_hours: Sequence[int]
) -> xr.Dataset:
    """Create a zero-wind fallback weather cube."""
    target_times = [ref_time + timedelta(hours=h) for h in horizons_hours]
    target_times_64 = [np.datetime64(t.astimezone(timezone.utc).replace(tzinfo=None), "ns") for t in target_times]

    shape = (len(target_times_64), len(window.lat), len(window.lon))

    coords = {
        "time": target_times_64,
        "lat": window.lat,
        "lon": window.lon,
        "lead_time_hours": ("time", list(horizons_hours))
    }

    return xr.Dataset(
        data_vars={
            "u10":  (("time", "lat", "lon"), np.zeros(shape, dtype=np.float32)),
            "v10":  (("time", "lat", "lon"), np.zeros(shape, dtype=np.float32)),
            "t2m":  (("time", "lat", "lon"), np.full(shape, np.nan, dtype=np.float32)),
            "rh2m": (("time", "lat", "lon"), np.full(shape, np.nan, dtype=np.float32)),
            # Zero precipitation assumed in fallback (conservative: no rain).
            "precip_24h": (("time", "lat", "lon"), np.zeros(shape, dtype=np.float32)),
            # DFMC is NaN in fallback — callers should treat as unknown moisture.
            "dfmc": (("time", "lat", "lon"), np.full(shape, np.nan, dtype=np.float32)),
        },
        coords=coords
    )

def _maybe_apply_weather_bias_correction(
    ds: xr.Dataset, *, weather_bias_corrector_path: Path | None = None
) -> xr.Dataset:
    """Apply a bias corrector if configured by arg or env var."""
    resolved = resolve_weather_bias_corrector_path(weather_bias_corrector_path, env_var=WEATHER_BIAS_CORRECTOR_ENV)
    if resolved is None:
        return ds
    if not resolved.exists():
        LOGGER.warning(
            "Weather bias corrector path does not exist (%s=%s); skipping correction.",
            WEATHER_BIAS_CORRECTOR_ENV,
            resolved,
        )
        return ds

    try:
        corrector = WeatherBiasCorrector.load_json(resolved)
        LOGGER.info(
            "Applied weather bias correction",
            extra={
                "corrector_path": str(resolved),
                "format_version": int(corrector.to_dict().get("format_version", -1)),
                "variables": sorted(list(getattr(corrector, "corrections", {}).keys())),
            },
        )
        out = corrector.apply(ds, inplace=False)
        # Attach lightweight provenance for downstream logging/persistence.
        try:
            out.attrs = dict(out.attrs or {})
            out.attrs["weather_bias_corrected"] = True
            out.attrs["weather_bias_corrector_path"] = str(resolved)
        except Exception:  # pragma: no cover
            pass
        return out
    except Exception:
        LOGGER.exception("Failed to load/apply weather bias corrector from %s; using uncorrected weather.", resolved)
        return ds


def build_spread_inputs(
    region_name: str | None,
    bbox: tuple[float, float, float, float],
    forecast_reference_time: datetime,
    *,
    horizons_hours: Sequence[int] = DEFAULT_HORIZONS_HOURS,
    fire_lookback_hours: int = 24,
    include_dem: bool = True,
    weight_by_denoised_score: bool = True,
    weather_bias_corrector_path: Path | None = None,
) -> SpreadInputs:
    """Assemble all required inputs for a spread model prediction.

    Parameters
    ----------
    region_name : str | None
        The name of the region (determines the analysis grid). If None, grid is created from bbox
        and terrain is set to empty (for location-based forecasting without pre-defined regions).
    bbox : tuple[float, float, float, float]
        The AOI bounding box (min_lon, min_lat, max_lon, max_lat).
    forecast_reference_time : datetime
        The T=0 time for the forecast.
    horizons_hours : Sequence[int], optional
        The forecast horizons in hours from reference time.
    fire_lookback_hours : int, optional
        How far back from reference time to look for active fires.
    include_dem : bool, optional
        Whether to include elevation in the terrain features.
    weight_by_denoised_score : bool, optional
        Whether to weight fire cells by their denoised score (default: True).

    Returns
    -------
    SpreadInputs
        The assembled and aligned inputs.
    """
    forecast_reference_time = _require_tz_aware_utc(
        forecast_reference_time, field_name="forecast_reference_time"
    )

    # 1. Resolve grid and window
    # If region_name is None, create grid from bbox (for location-based forecasting)
    if region_name is None:
        min_lon, min_lat, max_lon, max_lat = bbox
        grid = GridSpec.from_bbox(
            lat_min=min_lat,
            lat_max=max_lat,
            lon_min=min_lon,
            lon_max=max_lon,
        )
    else:
        grid = get_region_grid_spec(region_name)
    window = get_grid_window_for_bbox(grid, bbox, clip=True)

    # STOP-GEO-CRS / STOP-GEO-RES: grid must match the canonical analysis grid contract.
    assert_grid_alignment(grid)

    # 2. Load fires — current state and two historical windows.
    #
    # fire_t0   : last 6 hours  (covers at least one full VIIRS overpass)
    # fire_t6h  : 6-12 hours ago
    # fire_t12h : 12-18 hours ago
    #
    # These windows are 6h wide and non-overlapping so that the model channels carry
    # distinct temporal information.  The fire_lookback_hours parameter still controls
    # how far back the t0 window starts (for backward compatibility with callers that
    # rely on wider lookbacks).
    fire_t0_start = forecast_reference_time - timedelta(hours=max(fire_lookback_hours, 6))
    try:
        fires = get_fire_cells_heatmap(
            region_name=region_name,
            grid=grid if region_name is None else None,
            bbox=bbox,
            start_time=fire_t0_start,
            end_time=forecast_reference_time,
            weight_by_denoised_score=weight_by_denoised_score,
            mode="max" if weight_by_denoised_score else "presence",
            clip=True,
        )
    except Exception as e:
        LOGGER.exception(
            "Failed to load fire heatmap for region=%r bbox=%r",
            region_name,
            bbox,
        )
        raise RuntimeError(
            f"Failed to load fire heatmap for region={region_name!r} bbox={bbox!r} "
            f"start_time={fire_t0_start!r} end_time={forecast_reference_time!r}"
        ) from e
    if fires.grid != grid:
        raise ValueError("Fire heatmap grid does not match region grid spec.")
    _assert_same_window(expected=window, actual=fires.window, label="active_fires")

    # Historical fire windows (best-effort — None on any query failure).
    fire_history_t6h: FireHeatmapWindow | None = None
    fire_history_t12h: FireHeatmapWindow | None = None
    for lag_start_h, lag_end_h, attr_name in [
        (12, 6,  "fire_history_t6h"),
        (18, 12, "fire_history_t12h"),
    ]:
        t_start = forecast_reference_time - timedelta(hours=lag_start_h)
        t_end   = forecast_reference_time - timedelta(hours=lag_end_h)
        try:
            hist = get_fire_cells_heatmap(
                region_name=region_name,
                grid=grid if region_name is None else None,
                bbox=bbox,
                start_time=t_start,
                end_time=t_end,
                weight_by_denoised_score=weight_by_denoised_score,
                mode="max" if weight_by_denoised_score else "presence",
                clip=True,
            )
            if attr_name == "fire_history_t6h":
                fire_history_t6h = hist
            else:
                fire_history_t12h = hist
        except Exception:
            LOGGER.warning(
                "Failed to load historical fire window %s (start=%s, end=%s); "
                "fire history channel will be None.",
                attr_name, t_start, t_end,
            )

    # 3. Load terrain (optional - create empty terrain if region_name is None or terrain unavailable)
    terrain_fallback_used = False
    if region_name is None:
        # Create empty terrain for location-based forecasting
        LOGGER.info("No region_name provided; using empty terrain (terrain features disabled)")
        from api.terrain.window import TerrainWindow
        terrain = TerrainWindow(
            window=window,
            slope=np.zeros((window.lat.size, window.lon.size), dtype=np.float32),
            aspect=np.zeros((window.lat.size, window.lon.size), dtype=np.float32),
            elevation=np.zeros((window.lat.size, window.lon.size), dtype=np.float32) if include_dem else None,
            valid_data_mask=np.ones((window.lat.size, window.lon.size), dtype=bool),
            aoi_mask=None,
        )
        terrain_fallback_used = True
    else:
        try:
            terrain = load_terrain_window(
                region_name=region_name,
                bbox=bbox,
                include_dem=include_dem,
                clip=True,
            )
        except Exception as e:
            LOGGER.warning(
                "Failed to load terrain for region=%r bbox=%r; using empty terrain. Error: %s",
                region_name,
                bbox,
                e,
            )
            # Fallback to empty terrain if region exists but terrain load fails
            from api.terrain.window import TerrainWindow
            terrain = TerrainWindow(
                window=window,
                slope=np.zeros((window.lat.size, window.lon.size), dtype=np.float32),
                aspect=np.zeros((window.lat.size, window.lon.size), dtype=np.float32),
                elevation=np.zeros((window.lat.size, window.lon.size), dtype=np.float32) if include_dem else None,
                valid_data_mask=np.ones((window.lat.size, window.lon.size), dtype=bool),
                aoi_mask=None,
            )
            terrain_fallback_used = True
    _assert_same_window(expected=window, actual=terrain.window, label="terrain")

    # 4. Load weather
    weather = _load_weather_cube(
        ref_time=forecast_reference_time,
        window=window,
        horizons_hours=horizons_hours,
        bbox=bbox,
        weather_bias_corrector_path=weather_bias_corrector_path,
    )
    # Basic contract checks for downstream models.
    if not all(d in weather.dims for d in ("time", "lat", "lon")):
        raise ValueError(f"weather_cube must include dims time/lat/lon; got dims={dict(weather.dims)!r}")
    if int(weather.sizes.get("lat", 0)) != int(window.lat.size) or int(weather.sizes.get("lon", 0)) != int(
        window.lon.size
    ):
        raise ValueError(
            "weather_cube spatial dims do not match window. "
            f"weather(lat,lon)=({int(weather.sizes.get('lat', 0))},{int(weather.sizes.get('lon', 0))}) "
            f"window=({int(window.lat.size)},{int(window.lon.size)})"
        )
    if "lat" in weather.coords and not np.allclose(
        np.asarray(weather.coords["lat"].values), np.asarray(window.lat), rtol=0.0, atol=1e-12
    ):
        raise ValueError("weather_cube.lat does not match window.lat")
    if "lon" in weather.coords and not np.allclose(
        np.asarray(weather.coords["lon"].values), np.asarray(window.lon), rtol=0.0, atol=1e-12
    ):
        raise ValueError("weather_cube.lon does not match window.lon")

    # Check if weather fallback was used (from weather cube attributes)
    weather_fallback_used = bool(getattr(weather, "attrs", {}).get("weather_fallback_used", False))
    if weather_fallback_used:
        LOGGER.warning(
            "Forecast using fallback weather data (zero-wind). "
            "Weather fallback reason: %s",
            getattr(weather, "attrs", {}).get("weather_fallback_reason", "unknown"),
        )

    return SpreadInputs(
        grid=grid,
        window=window,
        active_fires=fires,
        weather_cube=weather,
        terrain=terrain,
        forecast_reference_time=forecast_reference_time,
        horizons_hours=horizons_hours,
        weather_fallback_used=weather_fallback_used,
        terrain_fallback_used=terrain_fallback_used,
        fire_history_t6h=fire_history_t6h,
        fire_history_t12h=fire_history_t12h,
    )
