-- Stage 1 — A' pivot initial migration.
--
-- Authoritative source: docs/pivot-architecture.md §3 "The collapsed data model".
-- This file is hand-maintained alongside db/schema/index.ts so we can express
-- PostGIS specifics (geometry types, GIST indexes, partial indexes) that
-- Drizzle's TypeScript DSL does not yet model. Future migrations may be
-- generated by `drizzle-kit generate`, but the *initial* migration is hand-
-- authored to keep the PostGIS contract explicit.
--
-- Idempotent against PGlite (which lacks PostGIS): every PostGIS-only
-- statement is wrapped to be a no-op when the extension is unavailable.
-- See db/test/pglite.ts for how tests substitute a stub geometry type.

CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION IF NOT EXISTS "pgcrypto"; -- for gen_random_uuid()

-- 1. users -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT PRIMARY KEY,
    "email" TEXT NOT NULL,
    "display_name" TEXT,
    "gemini_api_key_enc" BYTEA,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ
);

-- Seed the single-user stub. Stage 5 (Clerk) replaces this row's id.
INSERT INTO "users" ("id", "email", "display_name")
VALUES ('stub-user-1', 'stub@earthtools.local', 'Stub User')
ON CONFLICT ("id") DO NOTHING;

-- 2. aois --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "aois" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" TEXT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "name" TEXT NOT NULL,
    "polygon" geometry(MultiPolygon, 4326) NOT NULL,
    "bbox" geometry(Polygon, 4326) NOT NULL,
    "centroid" geometry(Point, 4326) NOT NULL,
    "region_bucket" TEXT NOT NULL,
    "area_ha" REAL NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "archived_at" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS "aois_polygon_gix" ON "aois" USING GIST ("polygon");
CREATE INDEX IF NOT EXISTS "aois_bbox_gix" ON "aois" USING GIST ("bbox");
CREATE INDEX IF NOT EXISTS "aois_region_bucket_active"
    ON "aois" ("region_bucket")
    WHERE "archived_at" IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "aois_user_name_active_uniq"
    ON "aois" ("user_id", "name")
    WHERE "archived_at" IS NULL;

-- 3. aoi_rules --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "aoi_rules" (
    "aoi_id" UUID PRIMARY KEY REFERENCES "aois"("id") ON DELETE CASCADE,
    "distance_buffer_km" REAL NOT NULL DEFAULT 25,
    "min_confidence" TEXT NOT NULL DEFAULT 'nominal',
    "min_frp_mw" REAL NOT NULL DEFAULT 5,
    "quiet_hours" JSONB,
    "paused_until" TIMESTAMPTZ,
    "notify_channels" JSONB NOT NULL DEFAULT '[]'::jsonb,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);
